export const PHOTO_UPLOAD_STATUSES = Object.freeze({
  DRAFT_QUEUED: 'DRAFT_QUEUED',
  REPORT_LINK_UNKNOWN: 'REPORT_LINK_UNKNOWN',
  QUEUED: 'QUEUED',
  UPLOADING: 'UPLOADING',
  UPLOAD_PAUSED: 'UPLOAD_PAUSED',
  UPLOAD_RETRY_WAIT: 'UPLOAD_RETRY_WAIT',
  FAILED_UPLOAD: 'FAILED_UPLOAD',
  STORAGE_COMPLETE: 'STORAGE_COMPLETE',
  DB_PENDING: 'DB_PENDING',
  DB_RETRY_WAIT: 'DB_RETRY_WAIT',
  FAILED_DB: 'FAILED_DB',
  DISCARD_PENDING: 'DISCARD_PENDING',
  DONE: 'DONE',
})

export const PHOTO_UPLOAD_EVENTS = Object.freeze({
  REPORT_ID_PROVEN: 'REPORT_ID_PROVEN',
  REPORT_RESULT_AMBIGUOUS: 'REPORT_RESULT_AMBIGUOUS',
  DISCARD_REQUESTED: 'DISCARD_REQUESTED',
  WORKER_CLAIMED: 'WORKER_CLAIMED',
  TUS_COMPLETED: 'TUS_COMPLETED',
  UPLOAD_AUTH_OR_OFFLINE_PAUSE: 'UPLOAD_AUTH_OR_OFFLINE_PAUSE',
  UPLOAD_RETRYABLE_FAILURE: 'UPLOAD_RETRYABLE_FAILURE',
  UPLOAD_PERMANENT_FAILURE: 'UPLOAD_PERMANENT_FAILURE',
  REMOTE_COMPLETE_RECONCILED: 'REMOTE_COMPLETE_RECONCILED',
  REMOTE_INCOMPLETE_RECONCILED: 'REMOTE_INCOMPLETE_RECONCILED',
  UPLOAD_RESUME_READY: 'UPLOAD_RESUME_READY',
  UPLOAD_RETRY_DUE: 'UPLOAD_RETRY_DUE',
  MANUAL_UPLOAD_RETRY: 'MANUAL_UPLOAD_RETRY',
  BEGIN_DB_PHASE: 'BEGIN_DB_PHASE',
  DB_ROW_FOUND: 'DB_ROW_FOUND',
  DB_INSERT_SUCCEEDED: 'DB_INSERT_SUCCEEDED',
  DB_RETRYABLE_FAILURE: 'DB_RETRYABLE_FAILURE',
  DB_PERMANENT_FAILURE: 'DB_PERMANENT_FAILURE',
  DB_RETRY_DUE: 'DB_RETRY_DUE',
  MANUAL_DB_RETRY: 'MANUAL_DB_RETRY',
  DISCARD_CLEANUP_VERIFIED: 'DISCARD_CLEANUP_VERIFIED',
  DISCARD_EXISTING_DB_ROW_RETAINED: 'DISCARD_EXISTING_DB_ROW_RETAINED',
})

export class InvalidPhotoUploadTransitionError extends Error {
  constructor(status, event) {
    super(`Invalid photo upload transition: ${String(status)} + ${String(event)}`)
    this.name = 'InvalidPhotoUploadTransitionError'
    this.status = status
    this.event = event
  }
}

const S = PHOTO_UPLOAD_STATUSES
const E = PHOTO_UPLOAD_EVENTS

const STATE = (status) => Object.freeze({ kind: 'STATE', status })
const DELETE_LOCAL = Object.freeze({ kind: 'DELETE_LOCAL' })

const TRANSITIONS = Object.freeze({
  [`${S.DRAFT_QUEUED}::${E.REPORT_ID_PROVEN}`]: STATE(S.QUEUED),
  [`${S.DRAFT_QUEUED}::${E.REPORT_RESULT_AMBIGUOUS}`]: STATE(S.REPORT_LINK_UNKNOWN),
  [`${S.DRAFT_QUEUED}::${E.DISCARD_REQUESTED}`]: DELETE_LOCAL,

  [`${S.REPORT_LINK_UNKNOWN}::${E.REPORT_ID_PROVEN}`]: STATE(S.QUEUED),
  [`${S.REPORT_LINK_UNKNOWN}::${E.DISCARD_REQUESTED}`]: DELETE_LOCAL,

  [`${S.QUEUED}::${E.WORKER_CLAIMED}`]: STATE(S.UPLOADING),
  [`${S.QUEUED}::${E.DISCARD_REQUESTED}`]: DELETE_LOCAL,

  [`${S.UPLOADING}::${E.TUS_COMPLETED}`]: STATE(S.STORAGE_COMPLETE),
  [`${S.UPLOADING}::${E.UPLOAD_AUTH_OR_OFFLINE_PAUSE}`]: STATE(S.UPLOAD_PAUSED),
  [`${S.UPLOADING}::${E.UPLOAD_RETRYABLE_FAILURE}`]: STATE(S.UPLOAD_RETRY_WAIT),
  [`${S.UPLOADING}::${E.UPLOAD_PERMANENT_FAILURE}`]: STATE(S.FAILED_UPLOAD),
  [`${S.UPLOADING}::${E.REMOTE_COMPLETE_RECONCILED}`]: STATE(S.STORAGE_COMPLETE),
  [`${S.UPLOADING}::${E.REMOTE_INCOMPLETE_RECONCILED}`]: STATE(S.QUEUED),
  [`${S.UPLOADING}::${E.DISCARD_REQUESTED}`]: STATE(S.DISCARD_PENDING),

  [`${S.UPLOAD_PAUSED}::${E.UPLOAD_RESUME_READY}`]: STATE(S.QUEUED),
  [`${S.UPLOAD_PAUSED}::${E.DISCARD_REQUESTED}`]: DELETE_LOCAL,

  [`${S.UPLOAD_RETRY_WAIT}::${E.UPLOAD_RETRY_DUE}`]: STATE(S.UPLOADING),
  [`${S.UPLOAD_RETRY_WAIT}::${E.DISCARD_REQUESTED}`]: DELETE_LOCAL,

  [`${S.FAILED_UPLOAD}::${E.MANUAL_UPLOAD_RETRY}`]: STATE(S.QUEUED),
  [`${S.FAILED_UPLOAD}::${E.DISCARD_REQUESTED}`]: DELETE_LOCAL,

  [`${S.STORAGE_COMPLETE}::${E.BEGIN_DB_PHASE}`]: STATE(S.DB_PENDING),
  [`${S.STORAGE_COMPLETE}::${E.DISCARD_REQUESTED}`]: STATE(S.DISCARD_PENDING),

  [`${S.DB_PENDING}::${E.DB_ROW_FOUND}`]: STATE(S.DONE),
  [`${S.DB_PENDING}::${E.DB_INSERT_SUCCEEDED}`]: STATE(S.DONE),
  [`${S.DB_PENDING}::${E.DB_RETRYABLE_FAILURE}`]: STATE(S.DB_RETRY_WAIT),
  [`${S.DB_PENDING}::${E.DB_PERMANENT_FAILURE}`]: STATE(S.FAILED_DB),
  [`${S.DB_PENDING}::${E.DISCARD_REQUESTED}`]: STATE(S.DISCARD_PENDING),

  [`${S.DB_RETRY_WAIT}::${E.DB_RETRY_DUE}`]: STATE(S.DB_PENDING),
  [`${S.DB_RETRY_WAIT}::${E.DISCARD_REQUESTED}`]: STATE(S.DISCARD_PENDING),

  [`${S.FAILED_DB}::${E.MANUAL_DB_RETRY}`]: STATE(S.DB_PENDING),
  [`${S.FAILED_DB}::${E.DISCARD_REQUESTED}`]: STATE(S.DISCARD_PENDING),

  [`${S.DISCARD_PENDING}::${E.DISCARD_CLEANUP_VERIFIED}`]: DELETE_LOCAL,
  [`${S.DISCARD_PENDING}::${E.DISCARD_EXISTING_DB_ROW_RETAINED}`]: STATE(S.DONE),
})

export function isPhotoUploadStatus(value) {
  return Object.values(PHOTO_UPLOAD_STATUSES).includes(value)
}

function isPhotoUploadEvent(value) {
  return Object.values(PHOTO_UPLOAD_EVENTS).includes(value)
}

export function isUploadTransportPermitted(status) {
  return status === PHOTO_UPLOAD_STATUSES.UPLOADING
}

export function transitionPhotoUpload(status, event) {
  if (!isPhotoUploadStatus(status) || !isPhotoUploadEvent(event)) {
    throw new InvalidPhotoUploadTransitionError(status, event)
  }

  const decision = TRANSITIONS[`${status}::${event}`]
  if (!decision) {
    throw new InvalidPhotoUploadTransitionError(status, event)
  }

  return decision
}
